version: "2"
services:
  gtm:
    hostname: gtm
    build: ./back/
    volumes:
     - ./:/app
    ports:
     - "8000:8000"
    links:
     - mongo
  gtm-front:
    hostname: gtm-front
    build: ./front/
    volumes:
     - ./:/app
    ports:
     - "18000:8080"
    links:
     - tomcat
  mongo:
    hostname: mongo
    image: mongo
    ports:
     - "27017:27017"
  tomcat:
    hostname: tomcat
    image: tomcat
    ports:
     - "8080:8080"
