version: "2"
services:
  gtm:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    links:
      - db
  db:
    image: mongo
    hostname: mongomachine
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
