version: "2"
services:
  gtm:
    container_name: gtm
    hostname: gtm
    build: ./
    volumes:
     - ./:/app
    ports:
     - "8000:8000"
    links:
     - mongo
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    ports:
     - "27017:27017"
