version: "2"
services:
  gtm:
    build: ./back/
    volumes:
      - ./:/app
    ports:
      - "8000:8001"
    links:
      - mongo
  gtm-front:
    build: ./front/
    volumes:
      - ./:/app
    ports:
      - "18000:18001"
    links:
      - tomcat
  mongo:
    image: mongo
    ports:
      - "27017:27018"
  tomcat:
    image: tomcat
    ports:
      - "8080:8081"
